export const SEARCH_INDEX = [
  { title: "Home", href: "/", keywords: "home landing" },
  { title: "Features", href: "/features", keywords: "features capabilities" },
  { title: "Pricing", href: "/pricing", keywords: "pricing plans cost subscribe" },
  { title: "Support", href: "/support", keywords: "support help faq contact" },
  { title: "About", href: "/about", keywords: "about company team" },
  { title: "Login", href: "/login", keywords: "login signin sign in" },
  { title: "Sign Up", href: "/signup", keywords: "signup register account create" },
  { title: "Dashboard Overview", href: "/dashboard", keywords: "dashboard overview home" },
  { title: "AI Tools", href: "/dashboard/ai", keywords: "ai tools gpt assistant" },
  { title: "Email Generator", href: "/dashboard/email", keywords: "email generator write" },
  { title: "Meeting Summary", href: "/dashboard/meeting", keywords: "meeting summary notes" },
  { title: "Task Planner", href: "/dashboard/planner", keywords: "planner tasks todo plan" },
  { title: "Research Assistant", href: "/dashboard/research", keywords: "research summarize" },
  { title: "Daily Diary", href: "/dashboard/diary", keywords: "diary journal reflection chat" },
  { title: "Calendar", href: "/dashboard/calendar", keywords: "calendar schedule" },
  { title: "Focus Mode", href: "/dashboard/focus", keywords: "focus pomodoro deep work timer" },
  { title: "Music & ASMR", href: "/dashboard/music", keywords: "music asmr sounds ambient spotify" },
  { title: "Analytics", href: "/dashboard/analytics", keywords: "analytics stats reports" },
  { title: "Notifications", href: "/dashboard/notifications", keywords: "notifications alerts" },
  { title: "Settings", href: "/dashboard/settings", keywords: "settings preferences" },
];
